server:
  port: 6066
  servlet:
    session:
      timeout: 24h
      cookie:
        max-age: 24h

spring:
  profiles.active: dev
  datasource:
#    url: jdbc:h2:mem:testdb
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: PlLcIne8Syc9e28KSioAeA/Vzz8=
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  config: classpath:log4j2-spring.xml

cors:
  allowed-origins:
    - http://127.0.0.1:5173
    - http://localhost:5173
    - http://localhost:8080
    - http://192.168.1.200:5173
  allowed-methods:
    - HEAD
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true
